#!/usr/bin/env bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

volume() {
  SINK=$( pactl list short sinks | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' | head -n 1 )
  NOW=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
  #amixer get $SCONTROL $(capability)
  MT=$(pactl list sinks | grep '^[[:space:]]Mute:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's/.*Mute: \([a-z]*\).*/\1/')
  if [[ $MT == "no" ]] ; then
  	echo "🔊️ $NOW%"
  else
  	echo 🔇️
  fi
}

#------------------------------------------------------------------------

case $BLOCK_BUTTON in
  3) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;  # right click, mute/unmute
  4) pactl set-sink-volume @DEFAULT_SINK@ +5%  ;; # scroll up, increase
  5) pactl set-sink-volume @DEFAULT_SINK@ -5%  ;; # scroll down, decrease
esac

volume
